/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lms;

import java.awt.*;
import java.awt.event.WindowEvent;
import javax.swing.*;
import javax.swing.plaf.basic.BasicButtonUI;
import static javax.swing.JOptionPane.CANCEL_OPTION;
import static javax.swing.JOptionPane.NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;

/**
 *
 * @author User
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form courses
     */
    CardLayout cardLayout;
    public AdminPage() {
        initComponents();
        Component[] components = this.getContentPane().getComponents();
        for(Component component : components)
        {
            if(component instanceof JButton)
            {
                ((JButton) component).setUI(new BasicButtonUI());
                ((JButton) component).setFocusPainted(false);
            }
        }
        
        cardLayout = (CardLayout)(mainPanel.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePane = new javax.swing.JPanel();
        headingPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        add_course = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        del_faculty = new javax.swing.JButton();
        del_course = new javax.swing.JButton();
        update_course = new javax.swing.JButton();
        add_stud = new javax.swing.JButton();
        del_stud = new javax.swing.JButton();
        add_faculty = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Home Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(55, 38, 91));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headingPanel.setBackground(new java.awt.Color(55, 38, 91));
        headingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMIN");
        headingPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 140, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Home Page");
        headingPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin-home.png"))); // NOI18N
        headingPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        sidePane.add(headingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 80));

        add_course.setBackground(new java.awt.Color(126, 86, 218));
        add_course.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_course.setForeground(new java.awt.Color(255, 255, 255));
        add_course.setText("Add Course");
        add_course.setFocusable(false);
        add_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_courseActionPerformed(evt);
            }
        });
        sidePane.add(add_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 50));

        logout.setBackground(new java.awt.Color(126, 86, 218));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.setFocusable(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        sidePane.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 280, 50));

        del_faculty.setBackground(new java.awt.Color(126, 86, 218));
        del_faculty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        del_faculty.setForeground(new java.awt.Color(255, 255, 255));
        del_faculty.setText("Remove Faculty");
        del_faculty.setFocusable(false);
        del_faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_facultyActionPerformed(evt);
            }
        });
        sidePane.add(del_faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 280, 50));

        del_course.setBackground(new java.awt.Color(126, 86, 218));
        del_course.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        del_course.setForeground(new java.awt.Color(255, 255, 255));
        del_course.setText("Delete Course");
        del_course.setFocusable(false);
        del_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_courseActionPerformed(evt);
            }
        });
        sidePane.add(del_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 280, 50));

        update_course.setBackground(new java.awt.Color(126, 86, 218));
        update_course.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        update_course.setForeground(new java.awt.Color(255, 255, 255));
        update_course.setText("Update Course");
        update_course.setFocusable(false);
        update_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_courseActionPerformed(evt);
            }
        });
        sidePane.add(update_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 280, 50));

        add_stud.setBackground(new java.awt.Color(126, 86, 218));
        add_stud.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_stud.setForeground(new java.awt.Color(255, 255, 255));
        add_stud.setText("Add Student");
        add_stud.setFocusable(false);
        add_stud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_studActionPerformed(evt);
            }
        });
        sidePane.add(add_stud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 280, 50));

        del_stud.setBackground(new java.awt.Color(126, 86, 218));
        del_stud.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        del_stud.setForeground(new java.awt.Color(255, 255, 255));
        del_stud.setText("Remove Student");
        del_stud.setFocusable(false);
        del_stud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_studActionPerformed(evt);
            }
        });
        sidePane.add(del_stud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 280, 50));

        add_faculty.setBackground(new java.awt.Color(126, 86, 218));
        add_faculty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_faculty.setForeground(new java.awt.Color(255, 255, 255));
        add_faculty.setText("Add Faculty");
        add_faculty.setFocusable(false);
        add_faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_facultyActionPerformed(evt);
            }
        });
        sidePane.add(add_faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 280, 50));

        getContentPane().add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 1080));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel1, "jPanel1");

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel2, "jPanel2");

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel3, "jPanel3");

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel4, "jPanel4");

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel5, "jPanel5");

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel6, "jPanel6");

        jPanel7.setBackground(new java.awt.Color(51, 255, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel7, "jPanel7");

        jPanel8.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel8, "jPanel8");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 1640, 980));

        topPanel.setBackground(new java.awt.Color(55, 38, 91));
        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1640, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_courseActionPerformed
        cardLayout.show(mainPanel, "jPanel1");
    }//GEN-LAST:event_add_courseActionPerformed


    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int a = JOptionPane.showConfirmDialog(logout, "Are you sure you want to Logout?");
        switch (a) {
            case YES_OPTION -> {
                AdminLogin al = new AdminLogin();
                al.setVisible(true);
                this.dispose();
            }
            case NO_OPTION -> {
            }
            case CANCEL_OPTION -> {
            }
        }


    }//GEN-LAST:event_logoutActionPerformed

    private void del_facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_facultyActionPerformed
        cardLayout.show(mainPanel, "jPanel7");
    }//GEN-LAST:event_del_facultyActionPerformed

    private void add_facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_facultyActionPerformed
        cardLayout.show(mainPanel, "jPanel6");
    }//GEN-LAST:event_add_facultyActionPerformed

    private void del_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_courseActionPerformed
        cardLayout.show(mainPanel, "jPanel2");
    }//GEN-LAST:event_del_courseActionPerformed

    private void update_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_courseActionPerformed
        cardLayout.show(mainPanel, "jPanel3");
    }//GEN-LAST:event_update_courseActionPerformed

    private void add_studActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_studActionPerformed
        cardLayout.show(mainPanel, "jPanel4");
    }//GEN-LAST:event_add_studActionPerformed

    private void del_studActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_studActionPerformed
        cardLayout.show(mainPanel, "jPanel5");
    }//GEN-LAST:event_del_studActionPerformed

    public void close() {
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_course;
    private javax.swing.JButton add_faculty;
    private javax.swing.JButton add_stud;
    private javax.swing.JButton del_course;
    private javax.swing.JButton del_faculty;
    private javax.swing.JButton del_stud;
    private javax.swing.JPanel headingPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel sidePane;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton update_course;
    // End of variables declaration//GEN-END:variables
}
