/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lms;

import java.awt.*;
import javax.swing.*;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;

/**
 *
 * @author User
 */
public class FacultyHome extends javax.swing.JFrame {

    /**
     * Creates new form FacultyHome
     */
    CardLayout cardLayout;
    public FacultyHome() {
        initComponents();
        Component[] components = this.getContentPane().getComponents();
        for(Component component : components)
        {
            if(component instanceof JButton)
            {
                ((JButton) component).setUI(new BasicButtonUI());
                ((JButton) component).setFocusPainted(false);
            }
        }
        
        cardLayout = (CardLayout)(mainPanel.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        sidePane1 = new javax.swing.JPanel();
        headingPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        all_studs = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        queries = new javax.swing.JButton();
        assgnt = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Faculty Home Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel1, "jPanel1");

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel2, "jPanel2");

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel3, "jPanel3");

        jPanel4.setBackground(new java.awt.Color(102, 255, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1640, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel4, "jPanel4");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 1640, 980));

        sidePane1.setBackground(new java.awt.Color(55, 38, 91));
        sidePane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headingPanel1.setBackground(new java.awt.Color(55, 38, 91));
        headingPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("Home Page");
        headingPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FACULTY");
        headingPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 140, 60));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fac.png"))); // NOI18N
        headingPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        sidePane1.add(headingPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 80));

        all_studs.setBackground(new java.awt.Color(126, 86, 218));
        all_studs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        all_studs.setForeground(new java.awt.Color(255, 255, 255));
        all_studs.setText("All Students");
        all_studs.setFocusable(false);
        all_studs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_studsActionPerformed(evt);
            }
        });
        sidePane1.add(all_studs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 50));

        logout.setBackground(new java.awt.Color(126, 86, 218));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.setFocusable(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        sidePane1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 280, 50));

        queries.setBackground(new java.awt.Color(126, 86, 218));
        queries.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        queries.setForeground(new java.awt.Color(255, 255, 255));
        queries.setText("Queries");
        queries.setFocusable(false);
        queries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queriesActionPerformed(evt);
            }
        });
        sidePane1.add(queries, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 280, 50));

        assgnt.setBackground(new java.awt.Color(126, 86, 218));
        assgnt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        assgnt.setForeground(new java.awt.Color(255, 255, 255));
        assgnt.setText("Assignments");
        assgnt.setFocusable(false);
        assgnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assgntActionPerformed(evt);
            }
        });
        sidePane1.add(assgnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 280, 50));

        getContentPane().add(sidePane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 1080));

        topPanel.setBackground(new java.awt.Color(55, 38, 91));
        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1640, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void all_studsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_studsActionPerformed
        cardLayout.show(mainPanel, "jPanel1");
    }//GEN-LAST:event_all_studsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int a = JOptionPane.showConfirmDialog(logout, "Are you sure you want to Logout?");
        switch (a) {
            case YES_OPTION -> {
                FacultyLogin al = new FacultyLogin();
                al.setVisible(true);
                this.dispose();
            }
            case NO_OPTION -> {
            }
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void queriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queriesActionPerformed
        cardLayout.show(mainPanel, "jPanel2");
    }//GEN-LAST:event_queriesActionPerformed

    private void assgntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assgntActionPerformed
        cardLayout.show(mainPanel, "jPanel3");
    }//GEN-LAST:event_assgntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton all_studs;
    private javax.swing.JButton assgnt;
    private javax.swing.JPanel headingPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton queries;
    private javax.swing.JPanel sidePane1;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
