/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lms;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;

/**
 *
 * @author User
 */
public class StudentHome extends javax.swing.JFrame {

    /**
     * Creates new form StudentHome
     */
    public StudentHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePane1 = new javax.swing.JPanel();
        headingPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        all_courses = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        enrolled_courses = new javax.swing.JButton();
        assgnt = new javax.swing.JButton();
        faq = new javax.swing.JButton();
        ask_q = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Home Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane1.setBackground(new java.awt.Color(55, 38, 91));
        sidePane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headingPanel1.setBackground(new java.awt.Color(55, 38, 91));
        headingPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("Home Page");
        headingPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STUDENT");
        headingPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 140, 60));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student.png"))); // NOI18N
        headingPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        sidePane1.add(headingPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 80));

        all_courses.setBackground(new java.awt.Color(126, 86, 218));
        all_courses.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        all_courses.setForeground(new java.awt.Color(255, 255, 255));
        all_courses.setText("All Courses");
        all_courses.setFocusable(false);
        all_courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_coursesActionPerformed(evt);
            }
        });
        sidePane1.add(all_courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 50));

        logout.setBackground(new java.awt.Color(126, 86, 218));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.setFocusable(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        logout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                logoutKeyPressed(evt);
            }
        });
        sidePane1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 280, 50));

        enrolled_courses.setBackground(new java.awt.Color(126, 86, 218));
        enrolled_courses.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        enrolled_courses.setForeground(new java.awt.Color(255, 255, 255));
        enrolled_courses.setText("Enrolled Courses");
        enrolled_courses.setFocusable(false);
        enrolled_courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrolled_coursesActionPerformed(evt);
            }
        });
        sidePane1.add(enrolled_courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 280, 50));

        assgnt.setBackground(new java.awt.Color(126, 86, 218));
        assgnt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        assgnt.setForeground(new java.awt.Color(255, 255, 255));
        assgnt.setText("Assignments");
        assgnt.setFocusable(false);
        assgnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assgntActionPerformed(evt);
            }
        });
        sidePane1.add(assgnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 280, 50));

        faq.setBackground(new java.awt.Color(126, 86, 218));
        faq.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        faq.setForeground(new java.awt.Color(255, 255, 255));
        faq.setText("FAQ");
        faq.setFocusable(false);
        faq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faqActionPerformed(evt);
            }
        });
        sidePane1.add(faq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 280, 50));

        ask_q.setBackground(new java.awt.Color(126, 86, 218));
        ask_q.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ask_q.setForeground(new java.awt.Color(255, 255, 255));
        ask_q.setText("ASK");
        ask_q.setFocusable(false);
        ask_q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ask_qActionPerformed(evt);
            }
        });
        sidePane1.add(ask_q, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 280, 50));

        getContentPane().add(sidePane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 1080));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 1640, 980));

        jPanel1.setBackground(new java.awt.Color(55, 38, 91));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1640, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void all_coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_coursesActionPerformed

    }//GEN-LAST:event_all_coursesActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int a = JOptionPane.showConfirmDialog(logout, "Are you sure you want to Logout?");
        switch (a) {
            case YES_OPTION -> {
                StudLogin al = new StudLogin();
                al.setVisible(true);
                this.dispose();
            }
            case NO_OPTION -> {
            }
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void enrolled_coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrolled_coursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrolled_coursesActionPerformed

    private void assgntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assgntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assgntActionPerformed

    private void faqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faqActionPerformed

    private void ask_qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ask_qActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ask_qActionPerformed

    private void logoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logoutKeyPressed

    }//GEN-LAST:event_logoutKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton all_courses;
    private javax.swing.JButton ask_q;
    private javax.swing.JButton assgnt;
    private javax.swing.JButton enrolled_courses;
    private javax.swing.JButton faq;
    private javax.swing.JPanel headingPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel sidePane1;
    // End of variables declaration//GEN-END:variables
}
